# Generated by Django 5.0.1 on 2024-02-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_unchained', '0002_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discriptline',
            new_name='Descriptor',
        ),
        migrations.RenameModel(
            old_name='Stugent',
            new_name='Student',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(related_name='courses', to='django_unchained.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_unchained.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_unchained.course')),
            ],
        ),
    ]
