# Generated by Django 5.0.2 on 2024-04-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_unchained', '0009_samplerecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleRecommendation',
        ),
    ]
